name: Deploy TO GAE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/7582543974/locations/global/workloadIdentityPools/my-pool/providers/github'
        project_id: 7582543974

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
